### 0. 파일 경로 지정

In [2]:
import pandas as pd
import numpy as np

from pathlib import Path
parent_path = Path.cwd().parent # 상위 폴더로 이동
file_path = parent_path/'W2_assignment'

### 1. Penguin.csv Open
penguins.csv 를 불러온 뒤 변수에 저장하고 상위 5개의 행 출력

In [3]:
df = pd.read_csv(file_path/'penguins.csv') # datafram으로 penguins.csv 불러오기
# read_csv() 를 꼭 달아줘야함

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

### 2. 데이터 정보 확인
데이터프레임의 전체 행 수, 컬럼별 데이터 타입, Non-null(결측치가 아닌) 개수를 확인하는 함수를 실행하세요.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

### 3. 결측지 개수 파악
각 컬럼별로 결측치(NaN)가 총 몇 개씩 있는지 확인하세요.

In [16]:
colList = df.columns.tolist()

for i in colList:
    print(f"컬럼 {i:18}에는 {df[i].isna().sum()}개의 결측치가 있습니다.")

컬럼 species           에는 0개의 결측치가 있습니다.
컬럼 island            에는 0개의 결측치가 있습니다.
컬럼 bill_length_mm    에는 2개의 결측치가 있습니다.
컬럼 bill_depth_mm     에는 2개의 결측치가 있습니다.
컬럼 flipper_length_mm 에는 2개의 결측치가 있습니다.
컬럼 body_mass_g       에는 2개의 결측치가 있습니다.
컬럼 sex               에는 11개의 결측치가 있습니다.

### 4. 결측치 처리 (행 삭제)
결측치가 하나라도 포함된 행을 모두 제거하고, 그 결과를 df_clean이라는 새로운 변수에 저장하세요. (이후 문제는 df_clean을 사용합니다.)

In [23]:
df_copied = df.copy()
df_clean = df_copied.dropna()

# df_clean.info() 를 통해 결측치 삭제 되었는 지 확인
df_clean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

### 5. 조건 필터링 (단일 조건)
species 가 Adelie 인 펭귄 출력

In [27]:
df_clean['species'] == 'Adelie'

0       True
1       True
2       True
4       True
5       True
       ...
338    False
340    False
341    False
342    False
343    False
Name: species, Length: 333, dtype: bool

### 6. 조건 필터링 (다중 조건)

In [31]:
df_clean[ (df_clean['island'] == 'Torgersen') & (df_clean['body_mass_g'] > 4000) ]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,Male
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
73,Adelie,Torgersen,45.8,18.9,197.0,4150.0,Male
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,Male
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,Male
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,Male
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,Male