# chap 5

목차
1. XGBoost 기능
2. XGBoost 파라미터 최적화
3. 모델링
4. 힉스 보손 찾기

## XGBoost 기능

1. 누락된 값 처리: missing 매개변수를 통해 자체적으로 누락된 값을 처리할 수 있다. 누락된 값이 들어갈 가능한 노드 분할마다 점수를 매겨서 최대한 높은 점수를 내는 분할을 선택한다.
2. 분할 탐색 알고리즘: 논문 참고 https://arxiv.org/pdf/1603.02754
3. 병렬 컴퓨팅: 데이터를 블록이란 단위로 정렬하므로 여러대의 컴퓨터에 분산 가능
4. 캐시 고려 접근: https://gist.github.com/jboner/2841832 과 논문 참고
5. 블록 압축과 샤딩: 논문 참고
6. 자체적 규제로 정확도 향상

## 2. XGBoost 파라미터 최적화

XGBoost의 전체 목적 함수는 손실 함수와 규제항의 합으로 이루어져 있다
$$\mathcal{L}(\phi) = \sum_{i} l(\hat{y}_i, y_i) + \sum_{k} \Omega(f_k)$$

### 손실함수

### 규제항

## 3. 모델링

### 붓꽃 데이터셋

In [3]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris() # 붓꽃 데이터셋 로드

In [4]:
df = pd.DataFrame(data=np.c_[iris['data'], iris['target']],     # np.c_ # 두 넘파이 배열을 합친다
                  columns=iris['feature_names'] + ['target'])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0

In [6]:
from sklearn.model_selection import train_test_split
y = df['target']
X = df.drop('target', axis=1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=2
)

In [10]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# 파라미터 세부 내용은 chap6에서
xgb = XGBClassifier(booster='gbtree',              # 기본 학습기
                    objective='multi:softprob', max_depth=6, 
                    learning_rate=0.1, n_estimators=100, n_jobs=-1, eval_metric='mlogloss')

xgb.fit(X_train, y_train, eval_set=[(X_train, y_train), (X_test, y_test)])
y_pred = xgb.predict(X_test)
score = accuracy_score(y_test, y_pred)
print(f"score: {score}")

[0]	validation_0-mlogloss:0.96661	validation_1-mlogloss:0.97486
[1]	validation_0-mlogloss:0.85681	validation_1-mlogloss:0.86795
[2]	validation_0-mlogloss:0.76341	validation_1-mlogloss:0.77734
[3]	validation_0-mlogloss:0.68313	validation_1-mlogloss:0.69975
[4]	validation_0-mlogloss:0.61356	validation_1-mlogloss:0.63281
[5]	validation_0-mlogloss:0.55288	validation_1-mlogloss:0.57413
[6]	validation_0-mlogloss:0.49966	validation_1-mlogloss:0.52347
[7]	validation_0-mlogloss:0.45281	validation_1-mlogloss:0.47910
[8]	validation_0-mlogloss:0.41140	validation_1-mlogloss:0.44014
[9]	validation_0-mlogloss:0.37468	validation_1-mlogloss:0.40584
[10]	validation_0-mlogloss:0.34216	validation_1-mlogloss:0.37607
[11]	validation_0-mlogloss:0.31315	validation_1-mlogloss:0.34979
[12]	validation_0-mlogloss:0.28722	validation_1-mlogloss:0.32655
[13]	validation_0-mlogloss:0.26401	validation_1-mlogloss:0.30600
[14]	validation_0-mlogloss:0.24320	validation_1-mlogloss:0.28780
[15]	validation_0-mlogloss:0.22450	validation_1-mlogloss:0.27170
[16]	validation_0-mlogloss:0.20760	validation_1-mlogloss:0.25725
[17]	validation_0-mlogloss:0.19237	validation_1-mlogloss:0.24445
[18]	validation_0-mlogloss:0.17861	validation_1-mlogloss:0.23310
[19]	validation_0-mlogloss:0.16617	validation_1-mlogloss:0.22320
[20]	validation_0-mlogloss:0.15490	validation_1-mlogloss:0.21431
[21]	validation_0-mlogloss:0.14459	validation_1-mlogloss:0.20594
[22]	validation_0-mlogloss:0.13534	validation_1-mlogloss:0.19904
[23]	validation_0-mlogloss:0.12694	validation_1-mlogloss:0.19296
[24]	validation_0-mlogloss:0.11914	validation_1-mlogloss:0.18726
[25]	validation_0-mlogloss:0.11219	validation_1-mlogloss:0.18260
[26]	validation_0-mlogloss:0.10597	validation_1-mlogloss:0.17835
[27]	validation_0-mlogloss:0.10017	validation_1-mlogloss:0.17443
[28]	validation_0-mlogloss:0.09486	validation_1-mlogloss:0.17130
[29]	validation_0-mlogloss:0.09003	validation_1-mlogloss:0.16832
[30]	validation_0-mlogloss:0.08521	validation_1-mlogloss:0.16590
[31]	validation_0-mlogloss:0.08093	validation_1-mlogloss:0.16375
[32]	validation_0-mlogloss:0.07700	validation_1-mlogloss:0.16191
[33]	validation_0-mlogloss:0.07349	validation_1-mlogloss:0.16033
[34]	validation_0-mlogloss:0.07014	validation_1-mlogloss:0.15902
[35]	validation_0-mlogloss:0.06705	validation_1-mlogloss:0.15794
[36]	validation_0-mlogloss:0.06409	validation_1-mlogloss:0.15711
[37]	validation_0-mlogloss:0.06122	validation_1-mlogloss:0.15613
[38]	validation_0-mlogloss:0.05890	validation_1-mlogloss:0.15581
[39]	validation_0-mlogloss:0.05685	validation_1-mlogloss:0.15518
[40]	validation_0-mlogloss:0.05482	validation_1-mlogloss:0.15480
[41]	validation_0-mlogloss:0.05293	validation_1-mlogloss:0.15453
[42]	validation_0-mlogloss:0.05120	validation_1-mlogloss:0.15477
[43]	validation_0-mlogloss:0.04950	validation_1-mlogloss:0.15516
[44]	validation_0-mlogloss:0.04795	validation_1-mlogloss:0.15551
[45]	validation_0-mlogloss:0.04645	validation_1-mlogloss:0.15604
[46]	validation_0-mlogloss:0.04507	validation_1-mlogloss:0.15648
[47]	validation_0-mlogloss:0.04382	validation_1-mlogloss:0.15708
[48]	validation_0-mlogloss:0.04263	validation_1-mlogloss:0.15728
[49]	validation_0-mlogloss:0.04146	validation_1-mlogloss:0.15784
[50]	validation_0-mlogloss:0.04056	validation_1-mlogloss:0.15799
[51]	validation_0-mlogloss:0.03961	validation_1-mlogloss:0.15819
[52]	validation_0-mlogloss:0.03880	validation_1-mlogloss:0.15856
[53]	validation_0-mlogloss:0.03794	validation_1-mlogloss:0.15881
[54]	validation_0-mlogloss:0.03720	validation_1-mlogloss:0.15909
[55]	validation_0-mlogloss:0.03653	validation_1-mlogloss:0.15953
[56]	validation_0-mlogloss:0.03588	validation_1-mlogloss:0.15993
[57]	validation_0-mlogloss:0.03555	validation_1-mlogloss:0.16060
[58]	validation_0-mlogloss:0.03511	validation_1-mlogloss:0.16126
[59]	validation_0-mlogloss:0.03473	validation_1-mlogloss:0.16178
[60]	validation_0-mlogloss:0.03439	validation_1-mlogloss:0.16254
[61]	validation_0-mlogloss:0.03409	validation_1-mlogloss:0.16285
[62]	validation_0-mlogloss:0.03379	validation_1-mlogloss:0.16300
[63]	validation_0-mlogloss:0.03354	validation_1-mlogloss:0.16298
[64]	validation_0-mlogloss:0.03328	validation_1-mlogloss:0.16359
[65]	validation_0-mlogloss:0.03287	validation_1-mlogloss:0.16388
[66]	validation_0-mlogloss:0.03262	validation_1-mlogloss:0.16446
[67]	validation_0-mlogloss:0.03241	validation_1-mlogloss:0.16489
[68]	validation_0-mlogloss:0.03205	validation_1-mlogloss:0.16525
[69]	validation_0-mlogloss:0.03178	validation_1-mlogloss:0.16595
[70]	validation_0-mlogloss:0.03143	validation_1-mlogloss:0.16668
[71]	validation_0-mlogloss:0.03125	validation_1-mlogloss:0.16678
[72]	validation_0-mlogloss:0.03092	validation_1-mlogloss:0.16714
[73]	validation_0-mlogloss:0.03070	validation_1-mlogloss:0.16774
[74]	validation_0-mlogloss:0.03039	validation_1-mlogloss:0.16844
[75]	validation_0-mlogloss:0.03022	validation_1-mlogloss:0.16855
[76]	validation_0-mlogloss:0.03004	validation_1-mlogloss:0.16897
[77]	validation_0-mlogloss:0.02987	validation_1-mlogloss:0.16907
[78]	validation_0-mlogloss:0.02958	validation_1-mlogloss:0.16944
[79]	validation_0-mlogloss:0.02938	validation_1-mlogloss:0.17001
[80]	validation_0-mlogloss:0.02921	validation_1-mlogloss:0.17043
[81]	validation_0-mlogloss:0.02905	validation_1-mlogloss:0.17050
[82]	validation_0-mlogloss:0.02889	validation_1-mlogloss:0.17092
[83]	validation_0-mlogloss:0.02874	validation_1-mlogloss:0.17102
[84]	validation_0-mlogloss:0.02859	validation_1-mlogloss:0.17143
[85]	validation_0-mlogloss:0.02844	validation_1-mlogloss:0.17183
[86]	validation_0-mlogloss:0.02829	validation_1-mlogloss:0.17193
[87]	validation_0-mlogloss:0.02814	validation_1-mlogloss:0.17234
[88]	validation_0-mlogloss:0.02795	validation_1-mlogloss:0.17243
[89]	validation_0-mlogloss:0.02781	validation_1-mlogloss:0.17250
[90]	validation_0-mlogloss:0.02766	validation_1-mlogloss:0.17291
[91]	validation_0-mlogloss:0.02742	validation_1-mlogloss:0.17291
[92]	validation_0-mlogloss:0.02725	validation_1-mlogloss:0.17348
[93]	validation_0-mlogloss:0.02707	validation_1-mlogloss:0.17390
[94]	validation_0-mlogloss:0.02683	validation_1-mlogloss:0.17391
[95]	validation_0-mlogloss:0.02663	validation_1-mlogloss:0.17445
[96]	validation_0-mlogloss:0.02650	validation_1-mlogloss:0.17485
[97]	validation_0-mlogloss:0.02625	validation_1-mlogloss:0.17481
[98]	validation_0-mlogloss:0.02607	validation_1-mlogloss:0.17523
[99]	validation_0-mlogloss:0.02583	validation_1-mlogloss:0.17518
score: 0.9736842105263158

### 당뇨병 데이터셋

In [11]:
X, y = datasets.load_diabetes(return_X_y=True)
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

xgb = XGBRegressor(booster='gbtree', objective='reg:squarederror',
                   max_depth=6, learning_rate=0.1, n_estimators=100, n_jobs=-1)
scores = cross_val_score(xgb, X, y, scoring='neg_root_mean_squared_error', cv=5)
rmse = -scores
print(f"rmse: {np.round(rmse, 3)}")
print(f"rmse 평균: {np.mean(rmse):.3f}")

rmse: [59.397 60.322 69.036 63.211 66.953]
rmse 평균: 63.784

In [12]:
# 비교를 위해 y의 통계량 확인
pd.DataFrame(y).describe()

                0
count  442.000000
mean   152.133484
std     77.093005
min     25.000000
25%     87.000000
50%    140.500000
75%    211.500000
max    346.000000

표준편차 이내이므로 괜찮은 결과임

## 4. 힉스 보손 찾기

In [11]:
from pathlib import Path
data_dir = Path.cwd().parents[2] / "04_Resources" / "Dataset" / "XGBoost"
df = pd.read_csv(data_dir / "atlas-higgs-challenge-2014-v2.csv.gz", nrows=250000, compression='gzip')
df.head()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt,Weight,Label,KaggleSet,KaggleWeight
0,100000,138.470,51.655,97.827,27.980,0.91,124.711,2.666,3.064,41.928,...,2.150,0.444,46.062,1.24,-2.475,113.497,0.000814,s,t,0.002653
1,100001,160.937,68.768,103.235,48.146,-999.00,-999.000,-999.000,3.473,2.078,...,0.725,1.158,-999.000,-999.00,-999.000,46.226,0.681042,b,t,2.233584
2,100002,-999.000,162.172,125.953,35.635,-999.00,-999.000,-999.000,3.148,9.336,...,2.053,-2.028,-999.000,-999.00,-999.000,44.251,0.715742,b,t,2.347389
3,100003,143.905,81.417,80.943,0.414,-999.00,-999.000,-999.000,3.310,0.414,...,-999.000,-999.000,-999.000,-999.00,-999.000,-0.000,1.660654,b,t,5.446378
4,100004,175.864,16.915,134.805,16.405,-999.00,-999.000,-999.000,3.891,16.405,...,-999.000,-999.000,-999.000,-999.00,-999.000,0.000,1.904263,b,t,6.245333

In [12]:
df_d = df.drop(['Weight', 'KaggleSet'], axis=1)
df_d = df_d.rename(columns={"KaggleWeight":"Weight"})
label_col = df_d['Label']
df_d = df_d.drop('Label', axis=1)
df_d['Label'] = label_col

In [13]:
df_d.head()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt,Weight,Label
0,100000,138.470,51.655,97.827,27.980,0.91,124.711,2.666,3.064,41.928,...,2,67.435,2.150,0.444,46.062,1.24,-2.475,113.497,0.002653,s
1,100001,160.937,68.768,103.235,48.146,-999.00,-999.000,-999.000,3.473,2.078,...,1,46.226,0.725,1.158,-999.000,-999.00,-999.000,46.226,2.233584,b
2,100002,-999.000,162.172,125.953,35.635,-999.00,-999.000,-999.000,3.148,9.336,...,1,44.251,2.053,-2.028,-999.000,-999.00,-999.000,44.251,2.347389,b
3,100003,143.905,81.417,80.943,0.414,-999.00,-999.000,-999.000,3.310,0.414,...,0,-999.000,-999.000,-999.000,-999.000,-999.00,-999.000,-0.000,5.446378,b
4,100004,175.864,16.915,134.805,16.405,-999.00,-999.000,-999.000,3.891,16.405,...,0,-999.000,-999.000,-999.000,-999.000,-999.00,-999.000,0.000,6.245333,b

In [14]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   EventId                      250000 non-null  int64
 1   DER_mass_MMC                 250000 non-null  float64
 2   DER_mass_transverse_met_lep  250000 non-null  float64
 3   DER_mass_vis                 250000 non-null  float64
 4   DER_pt_h                     250000 non-null  float64
 5   DER_deltaeta_jet_jet         250000 non-null  float64
 6   DER_mass_jet_jet             250000 non-null  float64
 7   DER_prodeta_jet_jet          250000 non-null  float64
 8   DER_deltar_tau_lep           250000 non-null  float64
 9   DER_pt_tot                   250000 non-null  float64
 10  DER_sum_pt                   250000 non-null  float64
 11  DER_pt_ratio_lep_tau         250000 non-null  float64
 12  DER_met_phi_centrality       250000 non-null  float64
 13  DER_lep_eta_centrality       250000 non-null  float64
 14  PRI_tau_pt                   250000 non-null  float64
 15  PRI_tau_eta                  250000 non-null  float64
 16  PRI_tau_phi                  250000 non-null  float64
 17  PRI_lep_pt                   250000 non-null  float64
 18  PRI_lep_eta                  250000 non-null  float64
 19  PRI_lep_phi                  250000 non-null  float64
 20  PRI_met                      250000 non-null  float64
 21  PRI_met_phi                  250000 non-null  float64
 22  PRI_met_sumet                250000 non-null  float64
 23  PRI_jet_num                  250000 non-null  int64
 24  PRI_jet_leading_pt           250000 non-null  float64
 25  PRI_jet_leading_eta          250000 non-null  float64
 26  PRI_jet_leading_phi          250000 non-null  float64
 27  PRI_jet_subleading_pt        250000 non-null  float64
 28  PRI_jet_subleading_eta       250000 non-null  float64
 29  PRI_jet_subleading_phi       250000 non-null  float64
 30  PRI_jet_all_pt               250000 non-null  float64
 31  Weight                       250000 non-null  float64
 32  Label                        250000 non-null  object
dtypes: float64(30), int64(2), object(1)
memory usage: 62.9+ MB

In [15]:
df_d['Label'] = df_d['Label'].replace({'s':1, 'b':0})
X = df_d.iloc[:,1:31]
y = df_d.iloc[:,-1]

C:\Users\devsa\AppData\Local\Temp\ipykernel_22956\520882430.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_d['Label'] = df_d['Label'].replace({'s':1, 'b':0})

In [16]:
df_d['test_Weight'] = df_d['Weight'] * 550000 / len(y)

In [17]:
s = np.sum(df_d[df_d['Label']==1]['test_Weight'])
b = np.sum(df_d[df_d['Label']==0]['test_Weight'])
b/s

np.float64(593.9401931492318)

In [19]:
# 1. 모델 객체 생성 (평가 지표 세팅은 여기서 끝냅니다!)
clf = XGBClassifier(
    n_estimators=120, 
    learning_rate=0.1, 
    missing=-999.0,          # 결측치(-999.0) 자동 처리
    scale_pos_weight=b/s,    # 클래스 불균형(Signal vs Background) 해소
    eval_metric=['auc', 'ams@0.15']  # ⭐️ fit 함수에 있던 채점 기준이 이쪽으로 이사 왔습니다!
)

# 2. 모델 학습 (fit에는 순수하게 데이터와 가중치만 들어갑니다)
clf.fit(
    X, y, 
    sample_weight=df_d['test_Weight'],          # 훈련 데이터의 가중치
    eval_set=[(X, y)],                        # 평가용 데이터 세트
    sample_weight_eval_set=[df_d['test_Weight']] # 평가 데이터의 가중치
)
clf.save_model('higgs-sklearn.model')
clf.evals_result()

[0]	validation_0-auc:0.91089	validation_0-ams@0.15:3.81632
[1]	validation_0-auc:0.91497	validation_0-ams@0.15:3.84984
[2]	validation_0-auc:0.91747	validation_0-ams@0.15:4.02133
[3]	validation_0-auc:0.91920	validation_0-ams@0.15:4.14473
[4]	validation_0-auc:0.92039	validation_0-ams@0.15:4.25783
[5]	validation_0-auc:0.92114	validation_0-ams@0.15:4.30765
[6]	validation_0-auc:0.92180	validation_0-ams@0.15:4.35496
[7]	validation_0-auc:0.92228	validation_0-ams@0.15:4.32385
[8]	validation_0-auc:0.92292	validation_0-ams@0.15:4.32770
[9]	validation_0-auc:0.92387	validation_0-ams@0.15:4.35540
[10]	validation_0-auc:0.92450	validation_0-ams@0.15:4.38447
[11]	validation_0-auc:0.92502	validation_0-ams@0.15:4.42677
[12]	validation_0-auc:0.92551	validation_0-ams@0.15:4.44712
[13]	validation_0-auc:0.92603	validation_0-ams@0.15:4.44548
[14]	validation_0-auc:0.92640	validation_0-ams@0.15:4.50608
[15]	validation_0-auc:0.92703	validation_0-ams@0.15:4.54460
[16]	validation_0-auc:0.92737	validation_0-ams@0.15:4.55510
[17]	validation_0-auc:0.92783	validation_0-ams@0.15:4.57233
[18]	validation_0-auc:0.92843	validation_0-ams@0.15:4.59664
[19]	validation_0-auc:0.92889	validation_0-ams@0.15:4.59870
[20]	validation_0-auc:0.92944	validation_0-ams@0.15:4.67576
[21]	validation_0-auc:0.92985	validation_0-ams@0.15:4.71991
[22]	validation_0-auc:0.93020	validation_0-ams@0.15:4.69486
[23]	validation_0-auc:0.93057	validation_0-ams@0.15:4.70505
[24]	validation_0-auc:0.93093	validation_0-ams@0.15:4.74869
[25]	validation_0-auc:0.93131	validation_0-ams@0.15:4.75267
[26]	validation_0-auc:0.93161	validation_0-ams@0.15:4.78320
[27]	validation_0-auc:0.93199	validation_0-ams@0.15:4.81308
[28]	validation_0-auc:0.93228	validation_0-ams@0.15:4.82922
[29]	validation_0-auc:0.93260	validation_0-ams@0.15:4.86395
[30]	validation_0-auc:0.93298	validation_0-ams@0.15:4.90680
[31]	validation_0-auc:0.93325	validation_0-ams@0.15:4.91192
[32]	validation_0-auc:0.93354	validation_0-ams@0.15:4.94707
[33]	validation_0-auc:0.93388	validation_0-ams@0.15:4.94611
[34]	validation_0-auc:0.93422	validation_0-ams@0.15:4.96176
[35]	validation_0-auc:0.93451	validation_0-ams@0.15:4.99506
[36]	validation_0-auc:0.93474	validation_0-ams@0.15:5.00724
[37]	validation_0-auc:0.93501	validation_0-ams@0.15:5.03059
[38]	validation_0-auc:0.93534	validation_0-ams@0.15:5.02836
[39]	validation_0-auc:0.93560	validation_0-ams@0.15:5.06225
[40]	validation_0-auc:0.93579	validation_0-ams@0.15:5.08493
[41]	validation_0-auc:0.93603	validation_0-ams@0.15:5.11222
[42]	validation_0-auc:0.93628	validation_0-ams@0.15:5.13229
[43]	validation_0-auc:0.93643	validation_0-ams@0.15:5.13978
[44]	validation_0-auc:0.93663	validation_0-ams@0.15:5.16735
[45]	validation_0-auc:0.93685	validation_0-ams@0.15:5.17644
[46]	validation_0-auc:0.93710	validation_0-ams@0.15:5.18864
[47]	validation_0-auc:0.93725	validation_0-ams@0.15:5.21680
[48]	validation_0-auc:0.93742	validation_0-ams@0.15:5.23979
[49]	validation_0-auc:0.93762	validation_0-ams@0.15:5.25381
[50]	validation_0-auc:0.93774	validation_0-ams@0.15:5.27639
[51]	validation_0-auc:0.93794	validation_0-ams@0.15:5.28436
[52]	validation_0-auc:0.93809	validation_0-ams@0.15:5.29951
[53]	validation_0-auc:0.93823	validation_0-ams@0.15:5.31280
[54]	validation_0-auc:0.93844	validation_0-ams@0.15:5.32302
[55]	validation_0-auc:0.93864	validation_0-ams@0.15:5.33345
[56]	validation_0-auc:0.93874	validation_0-ams@0.15:5.32255
[57]	validation_0-auc:0.93889	validation_0-ams@0.15:5.34157
[58]	validation_0-auc:0.93904	validation_0-ams@0.15:5.37503
[59]	validation_0-auc:0.93924	validation_0-ams@0.15:5.38840
[60]	validation_0-auc:0.93939	validation_0-ams@0.15:5.38875
[61]	validation_0-auc:0.93953	validation_0-ams@0.15:5.39571
[62]	validation_0-auc:0.93966	validation_0-ams@0.15:5.41060
[63]	validation_0-auc:0.93978	validation_0-ams@0.15:5.41427
[64]	validation_0-auc:0.93993	validation_0-ams@0.15:5.42139
[65]	validation_0-auc:0.94003	validation_0-ams@0.15:5.44051
[66]	validation_0-auc:0.94020	validation_0-ams@0.15:5.45284
[67]	validation_0-auc:0.94038	validation_0-ams@0.15:5.45022
[68]	validation_0-auc:0.94049	validation_0-ams@0.15:5.48075
[69]	validation_0-auc:0.94059	validation_0-ams@0.15:5.49106
[70]	validation_0-auc:0.94068	validation_0-ams@0.15:5.49290
[71]	validation_0-auc:0.94078	validation_0-ams@0.15:5.49369
[72]	validation_0-auc:0.94091	validation_0-ams@0.15:5.50676
[73]	validation_0-auc:0.94102	validation_0-ams@0.15:5.49234
[74]	validation_0-auc:0.94115	validation_0-ams@0.15:5.51235
[75]	validation_0-auc:0.94129	validation_0-ams@0.15:5.54476
[76]	validation_0-auc:0.94139	validation_0-ams@0.15:5.54560
[77]	validation_0-auc:0.94152	validation_0-ams@0.15:5.54532
[78]	validation_0-auc:0.94170	validation_0-ams@0.15:5.56316
[79]	validation_0-auc:0.94179	validation_0-ams@0.15:5.56896
[80]	validation_0-auc:0.94196	validation_0-ams@0.15:5.56996
[81]	validation_0-auc:0.94206	validation_0-ams@0.15:5.56987
[82]	validation_0-auc:0.94215	validation_0-ams@0.15:5.57340
[83]	validation_0-auc:0.94226	validation_0-ams@0.15:5.58800
[84]	validation_0-auc:0.94239	validation_0-ams@0.15:5.58075
[85]	validation_0-auc:0.94248	validation_0-ams@0.15:5.59268
[86]	validation_0-auc:0.94257	validation_0-ams@0.15:5.60123
[87]	validation_0-auc:0.94267	validation_0-ams@0.15:5.62230
[88]	validation_0-auc:0.94276	validation_0-ams@0.15:5.61945
[89]	validation_0-auc:0.94291	validation_0-ams@0.15:5.61283
[90]	validation_0-auc:0.94302	validation_0-ams@0.15:5.62970
[91]	validation_0-auc:0.94308	validation_0-ams@0.15:5.63972
[92]	validation_0-auc:0.94316	validation_0-ams@0.15:5.65623
[93]	validation_0-auc:0.94325	validation_0-ams@0.15:5.65714
[94]	validation_0-auc:0.94334	validation_0-ams@0.15:5.65999
[95]	validation_0-auc:0.94344	validation_0-ams@0.15:5.67458
[96]	validation_0-auc:0.94354	validation_0-ams@0.15:5.66859
[97]	validation_0-auc:0.94361	validation_0-ams@0.15:5.69129
[98]	validation_0-auc:0.94366	validation_0-ams@0.15:5.69183
[99]	validation_0-auc:0.94377	validation_0-ams@0.15:5.69637
[100]	validation_0-auc:0.94388	validation_0-ams@0.15:5.71186
[101]	validation_0-auc:0.94397	validation_0-ams@0.15:5.70522
[102]	validation_0-auc:0.94406	validation_0-ams@0.15:5.70735
[103]	validation_0-auc:0.94412	validation_0-ams@0.15:5.70940
[104]	validation_0-auc:0.94418	validation_0-ams@0.15:5.70959
[105]	validation_0-auc:0.94428	validation_0-ams@0.15:5.70281
[106]	validation_0-auc:0.94437	validation_0-ams@0.15:5.71544
[107]	validation_0-auc:0.94445	validation_0-ams@0.15:5.70513
[108]	validation_0-auc:0.94451	validation_0-ams@0.15:5.70471
[109]	validation_0-auc:0.94457	validation_0-ams@0.15:5.72450
[110]	validation_0-auc:0.94463	validation_0-ams@0.15:5.73820
[111]	validation_0-auc:0.94474	validation_0-ams@0.15:5.73811
[112]	validation_0-auc:0.94479	validation_0-ams@0.15:5.73584
[113]	validation_0-auc:0.94485	validation_0-ams@0.15:5.73782
[114]	validation_0-auc:0.94498	validation_0-ams@0.15:5.76624
[115]	validation_0-auc:0.94514	validation_0-ams@0.15:5.78128
[116]	validation_0-auc:0.94520	validation_0-ams@0.15:5.78301
[117]	validation_0-auc:0.94527	validation_0-ams@0.15:5.76474
[118]	validation_0-auc:0.94537	validation_0-ams@0.15:5.77180
[119]	validation_0-auc:0.94544	validation_0-ams@0.15:5.76973

c:\Users\devsa\anaconda3\Lib\site-packages\xgboost\sklearn.py:1118: UserWarning: [21:42:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\c_api\c_api.cc:1575: Saving model in the UBJSON format as default.  You can use a file extension: `json` or `ubj` to choose between formats.
  self.get_booster().save_model(fname)

{'validation_0': OrderedDict([('auc',
               [0.9108909137731261,
                0.9149737185044572,
                0.9174723014301981,
                0.9192029708224471,
                0.9203940085335051,
                0.9211376513413114,
                0.9217967898092925,
                0.9222785063838784,
                0.9229219023580477,
                0.9238680169316417,
                0.9244953049416742,
                0.9250236805694307,
                0.9255127456174714,
                0.9260268167533802,
                0.9264009591431044,
                0.9270345848801917,
                0.9273710462687623,
                0.9278304834943003,
                0.9284345352751293,
                0.9288914864604615,
                0.9294405579334073,
                0.9298507680796411,
                0.9302021632361616,
                0.9305693515828461,
                0.9309325386066278,
                0.9313093849747285,
                0.9316082226493826,
                0.9319941511239744,
                0.932276229453727,
                0.9326034041682396,
                0.9329767957750023,
                0.9332538991386514,
                0.933535492658325,
                0.9338841090610626,
                0.9342156615963879,
                0.9345112547754941,
                0.9347369258423969,
                0.9350058611698671,
                0.9353428454083234,
                0.9355958528918401,
                0.9357935362327688,
                0.9360323824707292,
                0.9362752423155862,
                0.9364318635996587,
                0.9366287031601537,
                0.9368502485816982,
                0.937097952124922,
                0.9372487949441498,
                0.9374231965266595,
                0.9376180451068161,
                0.9377443243890231,
                0.937937196137427,
                0.9380893658275068,
                0.9382327941456484,
                0.9384438153025997,
                0.9386436678563238,
                0.9387401955415512,
                0.9388851026422368,
                0.9390440278936004,
                0.9392419883560604,
                0.9393920027697288,
                0.9395342533122042,
                0.9396602270793207,
                0.9397793937121458,
                0.9399348830056161,
                0.9400310304413875,
                0.9401956482784913,
                0.9403790028998407,
                0.9404930165823231,
                0.9405945432458913,
                0.9406810323253318,
                0.9407830431095527,
                0.9409138124722116,
                0.9410224963686662,
                0.9411502434462151,
                0.9412864413293713,
                0.9413946379562314,
                0.9415188725715484,
                0.9416996490820329,
                0.9417875248314962,
                0.9419578649864573,
                0.9420597910281279,
                0.9421505516410321,
                0.9422565547089137,
                0.9423889689884298,
                0.9424777286663806,
                0.9425725000952137,
                0.9426658297327937,
                0.9427553962526114,
                0.9429146838986133,
                0.9430157689327758,
                0.9430775067218191,
                0.9431555933074021,
                0.9432492392690074,
                0.9433386085637249,
                0.943440932823343,
                0.9435404489547574,
                0.9436061949901167,
                0.9436632362034689,
                0.943769109949386,
                0.9438750832939643,
                0.943966358573309,
                0.9440558686473173,
                0.9441158462083703,
                0.944178732946961,
                0.9442750951801372,
                0.9443714223421091,
                0.9444467307505069,
                0.9445054228889821,
                0.9445697265342973,
                0.9446297663072372,
                0.9447389472951538,
                0.9447921428578442,
                0.9448548923584404,
                0.9449833917777426,
                0.9451359154043971,
                0.9451990918025333,
                0.9452684621569523,
                0.9453748568052227,
                0.9454357061585681]),
              ('ams@0.15',
               [3.8163177967071533,
                3.8498411178588867,
                4.021329402923584,
                4.144729137420654,
                4.257829189300537,
                4.307647705078125,
                4.354957580566406,
                4.323850631713867,
                4.327702045440674,
                4.355396270751953,
                4.384468078613281,
                4.426766872406006,
                4.447122097015381,
                4.445481777191162,
                4.506076812744141,
                4.544600963592529,
                4.5550994873046875,
                4.572332859039307,
                4.596635341644287,
                4.598696708679199,
                4.675762176513672,
                4.719906330108643,
                4.694864749908447,
                4.705047130584717,
                4.748691082000732,
                4.7526679039001465,
                4.783199787139893,
                4.813077449798584,
                4.829216957092285,
                4.863949775695801,
                4.906799793243408,
                4.911922454833984,
                4.947072982788086,
                4.946107864379883,
                4.96176290512085,
                4.995059013366699,
                5.007241249084473,
                5.0305914878845215,
                5.0283589363098145,
                5.062247276306152,
                5.084926605224609,
                5.112215995788574,
                5.132286071777344,
                5.139781475067139,
                5.167348384857178,
                5.176435470581055,
                5.188635349273682,
                5.21680212020874,
                5.239787578582764,
                5.253809928894043,
                5.2763872146606445,
                5.284364700317383,
                5.299505233764648,
                5.312795639038086,
                5.323019504547119,
                5.3334479331970215,
                5.322547912597656,
                5.341567516326904,
                5.375028610229492,
                5.388398170471191,
                5.388753414154053,
                5.395712852478027,
                5.410599231719971,
                5.4142656326293945,
                5.421394348144531,
                5.440509796142578,
                5.452838897705078,
                5.450222492218018,
                5.480748176574707,
                5.491057395935059,
                5.492900848388672,
                5.493686676025391,
                5.506763458251953,
                5.492341995239258,
                5.512349605560303,
                5.544758319854736,
                5.545602798461914,
                5.545318126678467,
                5.563157558441162,
                5.568960666656494,
                5.569955348968506,
                5.56986665725708,
                5.573401927947998,
                5.587997913360596,
                5.580752849578857,
                5.592683792114258,
                5.6012349128723145,
                5.6223039627075195,
                5.619447708129883,
                5.6128315925598145,
                5.62970495223999,
                5.639723300933838,
                5.6562323570251465,
                5.657140731811523,
                5.659987926483154,
                5.6745781898498535,
                5.668591499328613,
                5.691291332244873,
                5.691831588745117,
                5.6963653564453125,
                5.711857795715332,
                5.705215930938721,
                5.707352161407471,
                5.709397315979004,
                5.709593772888184,
                5.702808380126953,
                5.715440273284912,
                5.705133438110352,
                5.704705238342285,
                5.724496364593506,
                5.738195896148682,
                5.738108158111572,
                5.735835552215576,
                5.737821102142334,
                5.766240119934082,
                5.781275272369385,
                5.783013820648193,
                5.764740467071533,
                5.771798610687256,
                5.769729137420654])])}